const a =[
  {
    "_id": "5a8af6eada19637ea038a037",
    "index": 0,
    "guid": "db9d6ff4-2ca1-4dd0-bb9b-a1d3a2b37821",
    "isActive": true,
    "balance": "$3,298.04",
    "picture": "https://picsum.photos/300/200?image=",
    "age": 26,
    "eyeColor": "brown",
    "name": "Lorene Sexton",
    "gender": "female",
    "company": "PATHWAYS",
    "headline": "Results can yield a number of cool snippets in the search results. The great thing about this type of markup is that Google is always adding new features in the search results, so any future additions they add you are probably retroactively included.",
    "email": "lorenesexton@pathways.com",
    "phone": "+1 (815) 528-2027",
    "address": "683 Jamaica Avenue, Faywood, Virginia, 8763",
    "about": "Elit laboris laboris quis nulla magna incididunt consectetur dolore cupidatat et nisi proident. Anim dolor tempor deserunt fugiat aliquip adipisicing sit. Quis laborum incididunt excepteur nulla officia nisi adipisicing consectetur veniam irure aliquip ipsum. Lorem ad culpa minim aliqua sit.\r\n",
    "registered": "2014-03-06T04:42:00 -01:00",
    "latitude": -38.081599,
    "longitude": 122.859393,
    "tags": [
      "id",
      "sit",
      "mollit",
      "consequat",
      "amet",
      "commodo",
      "eiusmod"
    ]
  
},
  {
    "_id": "5a8af6ea5b5a636f4b9c9c16",
    "index": 1,
    "guid": "d675c668-0b02-48b0-bd45-82c6085c3636",
    "isActive": true,
    "balance": "$2,223.62",
    "picture": "https://picsum.photos/200/?image=",
    "age": 33,
    "eyeColor": "green",
    "name": "Christie Bean",
    "gender": "female",
    "company": "CYTRAK",
    "headline": "Without a doubt this is one of the more popular types of JSON-LD markup.",
    "email": "christiebean@cytrak.com",
    "phone": "+1 (930) 576-2931",
    "address": "490 Norwood Avenue, Kenmar, North Carolina, 4518",
    "about": "Officia est veniam minim in cillum. Ipsum veniam reprehenderit consectetur non anim cupidatat. Cupidatat ad consectetur ex ad anim labore culpa Lorem fugiat id est ex qui sunt. Eiusmod duis velit elit deserunt.\r\n",
    "registered": "2015-02-09T03:06:24 -01:00",
    "latitude": 22.182693,
    "longitude": 103.375151,
    "tags": [
      "id",
      "aute",
      "anim",
      "id",
      "fugiat",
      "non",
      "consequat"
    ]
  },
  {
    "_id": "5a8af6eab6de9180bc221dfe",
    "index": 2,
    "guid": "3e822dac-9966-49b1-98d3-802266dca51c",
    "isActive": true,
    "balance": "$1,659.78",
    "picture": "https://picsum.photos/300/100?image=",
    "age": 33,
    "eyeColor": "https://picsum.photos/200/300/",
    "gender": "female",
    "company": "ECOSYS",
    "headline": "validates just fine on Google’s Structured Data Testing Tool, and we are really excited to see what type of results it can yield.",
    "email": "lynnhewitt@ecosys.com",
    "phone": "+1 (920) 588-3947",
    "address": "824 Fiske Place, Buxton, Rhode Island, 201",
    "about": "Officia qui quis eiusmod duis deserunt non nulla duis culpa incididunt quis irure veniam. Reprehenderit incididunt commodo dolor magna et minim aute commodo laborum nostrud. Magna veniam sint velit exercitation ad magna aute adipisicing cillum reprehenderit.\r\n",
    "registered": "2014-04-06T09:01:43 -02:00",
    "latitude": 11.872458,
    "longitude": 39.848867,
    "tags": [
      "ea",
      "consequat",
      "in",
      "sint",
      "qui",
      "nostrud",
      "esse"
    ]
  },
  {
    "_id": "5a8af6ea95586ce82a840040",
    "index": 3,
    "guid": "6dfca35e-31bd-49ad-adf6-1811d4973981",
    "isActive": false,
    "balance": "$3,312.26",
    "picture": "https://picsum.photos/200/300?image=",
    "age": 29,
    "eyeColor": "green",
    "name": "Ellis Chapman",
    "gender": "male",
    "company": "DUOFLEX",
    "headline": "This is a type that we just discovered called “TechArticle” and according to schema.org it is meant for “How-to (task) topics, step-by-step, procedural troubleshooting, specifications, etc.",
    "email": "ellischapman@duoflex.com",
    "phone": "+1 (800) 533-2347",
    "address": "939 Norfolk Street, Sanders, American Samoa, 3419",
    "about": "Irure veniam tempor aliqua tempor ex excepteur cupidatat eiusmod dolor. Eu deserunt dolore dolor labore proident commodo magna. Irure dolor ad proident velit reprehenderit minim pariatur. Dolor enim ad id Lorem proident sint anim aliqua id quis veniam do nulla. Cupidatat Lorem esse nulla consectetur aliqua sint elit officia non. Fugiat velit incididunt proident cillum cupidatat ea labore duis consequat laborum exercitation Lorem commodo esse. Nisi duis tempor esse incididunt laborum nulla et aute do enim excepteur irure pariatur fugiat.\r\n",
    "registered": "2014-05-25T12:43:08 -02:00",
    "latitude": -55.714847,
    "longitude": -101.958303,
    "tags": [
      "pariatur",
      "id",
      "exercitation",
      "consequat",
      "eu",
      "qui",
      "magna"
    ]
  },
  {
    "_id": "5a8af6ea89d5c857320de3b2",
    "index": 4,
    "guid": "0c0296e4-0ff0-499b-8cb5-cdf6639e4749",
    "isActive": false,
    "balance": "$1,369.60",
    "picture": "https://picsum.photos/200/300?image=",
    "age": 27,
    "eyeColor": "blue",
    "name": "Lila James",
    "gender": "female",
    "company": "AVENETRO",
    "headline": "Before you go any further, make sure you know the difference between an article, a website, a blog, and a blog post.",
    "email": "lilajames@avenetro.com",
    "phone": "+1 (880) 550-3597",
    "address": "949 Rost Place, Beaulieu, Iowa, 6430",
    "about": "Magna mollit esse sunt incididunt duis incididunt sunt eu laborum sint. Dolor minim ipsum aliqua minim velit minim aliqua ea non. Anim enim sint ad est magna sit in laborum laborum consequat sit velit. Nulla reprehenderit officia aliqua laborum consectetur in labore veniam amet proident. Ullamco sit anim labore quis sint excepteur quis exercitation exercitation. Duis esse ex non occaecat officia amet dolore est laboris tempor laboris excepteur.\r\n",
    "registered": "2018-01-13T05:46:40 -01:00",
    "latitude": -13.621221,
    "longitude": 107.483689,
    "tags": [
      "cillum",
      "veniam",
      "non",
      "velit",
      "ut",
      "labore",
      "exercitation"
    ]
  },
  {
    "_id": "5a8af6ea95ebde0dc3cd5b57",
    "index": 5,
    "guid": "f7006128-c9bb-4124-b64b-72960c2fec9a",
    "isActive": true,
    "balance": "$2,515.55",
    "picture": "https://picsum.photos/200/100?image=",
    "age": 24,
    "eyeColor": "brown",
    "name": "Alexandra Flowers",
    "gender": "female",
    "company": "TRIBALOG",
    "headline": "Article markup can yield a lot of good stuff. Properly used, Google might bless your site with featues like “in the news”.",
    "email": "alexandraflowers@tribalog.com",
    "phone": "+1 (833) 411-3350",
    "address": "798 Hall Street, Dellview, Ohio, 6213",
    "about": "Enim occaecat dolore ullamco excepteur magna occaecat sint duis magna nostrud. Sunt deserunt culpa nisi ullamco cillum et sint aliquip ex. Aliquip ea qui excepteur ea deserunt minim exercitation aliqua sit labore officia. Adipisicing consectetur cupidatat id sint ipsum laboris eiusmod amet cupidatat pariatur dolore ad cupidatat. Amet culpa nulla ipsum magna fugiat minim. Sint ea aliquip velit dolore proident culpa et nisi aute ea dolore eiusmod sint dolor.\r\n",
    "registered": "2014-06-11T04:33:08 -02:00",
    "latitude": -86.053052,
    "longitude": 161.974783,
    "tags": [
      "sint",
      "deserunt",
      "culpa",
      "minim",
      "minim",
      "deserunt",
      "deserunt"
    ]
  },
  {
    "_id": "5a8af6ea9d156ff14f36269e",
    "index": 6,
    "guid": "6aff02cd-8516-4e58-a3e6-06d0a1e6fe7f",
    "isActive": true,
    "balance": "$1,257.37",
    "picture": "https://picsum.photos/200/300?image=",
    "age": 36,
    "eyeColor": "green",
    "name": "Roth Reilly",
    "gender": "male",
    "company": "QUANTALIA",
    "headline": "Article markup can yield a lot of good stuff. Properly used, Google might bless your site with featues like “in the news” as well as content carousels.",
    "email": "rothreilly@quantalia.com",
    "phone": "+1 (926) 436-2194",
    "address": "544 Sedgwick Place, Wilmington, Maine, 1103",
    "about": "Pariatur culpa consequat laborum est ullamco aliqua aliquip laboris sint anim tempor. Eiusmod cupidatat Lorem voluptate aliqua ut Lorem velit adipisicing velit mollit. Eu id minim excepteur esse.\r\n",
    "registered": "2016-11-09T09:45:22 -01:00",
    "latitude": -23.615821,
    "longitude": 12.750735,
    "tags": [
      "officia",
      "aliqua",
      "ex",
      "adipisicing",
      "ipsum",
      "proident",
      "aliqua"
    ]
  }
];
export default a;